server/apps/base/urls.py
from django.urls import path

from server.apps.base.views import AboutView, ContactView, HomeView

app_name = "base"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("about/", AboutView.as_view(), name="about"),
    path("contact/", ContactView.as_view(), name="contact"),
]

server/apps/category/urls.py
from django.urls import path

from server.apps.category.views import CategoryView

app_name = "products"

urlpatterns = [
    path("category/<int:pk>/", CategoryView.as_view(), name="detail"),
]

server/apps/product/urls.py
from django.urls import path

from server.apps.product.views import ProductDetailView, ProductListView

app_name = "products"

urlpatterns = [
    path("", ProductListView.as_view(), name="list"),
    path("product/<int:pk>/", ProductDetailView.as_view(), name="detail"),
]

server/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("server.apps.base.urls", namespace="base")),
    path("shop/", include("server.apps.product.urls", namespace="product")),
    path("category/", include("server.apps.category.urls", namespace="category")),
]


# Django Health Check
urlpatterns += [
    path("health/", include("health_check.urls")),
]

if settings.DEBUG:
    from django.conf.urls.static import static  # noqa: WPS433

    # Django Debug Toolbar
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

    # Serving media files in development only:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

server/apps/base/models.py
from django.db import models


class BaseSetting(models.Model):
    """Model definition for BaseSetting."""

    company_name = models.CharField(verbose_name="Company Name", max_length=255)
    advert = models.CharField(verbose_name="Advertisement", max_length=50)
    email = models.EmailField(verbose_name="Email", max_length=255)
    phone = models.CharField(verbose_name="Phone", max_length=255)
    facebook = models.CharField(verbose_name="Facebook", max_length=255)
    instagram = models.CharField(verbose_name="Instagram", max_length=255)
    address = models.CharField(verbose_name="Address", max_length=255)
    address_url = models.CharField(verbose_name="Address URL", max_length=255)

    class Meta:
        """Meta definition for BaseSetting."""

        verbose_name = "BaseSetting"
        verbose_name_plural = "BaseSettings"

    def __str__(self):
        """Unicode representation of BaseSetting."""
        return self.company_name

server/apps/category/models.py
from django.db import models

from server.apps.product.models import Product


class Category(models.Model):
    """Model definition for Category."""

    name = models.CharField(max_length=255)
    main = models.ForeignKey("self", on_delete=models.CASCADE, related_name="children", null=True, blank=True)

    class Meta:
        """Meta definition for Category."""

        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        """Unicode representation of Category."""
        return self.name

    def get_products(self):
        """Return all products in this category and its children."""
        return Product.objects.filter(categories__in=[self] + list(self.children.all())).distinct()

server/apps/product/models.py
from django.db import models

from server.apps.product.logic.querysets import ProductQuerySet


class Product(models.Model):
    """Model definition for Product."""

    name = models.CharField(max_length=255)
    categories = models.ManyToManyField("category.Category", related_name="products")
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    description = models.TextField()

    objects = ProductQuerySet.as_manager()

    class Meta:
        """Meta definition for Product."""

        verbose_name = "Product"
        verbose_name_plural = "Products"

    def __str__(self):
        """Unicode representation of Product."""
        return self.name

    @property
    def image(self):
        return self.images.first().image if self.images.exists() else None

    @property
    def get_categories(self):
        return ", ".join([c.name for c in self.categories.all()])

    @property
    def related_products(self):
        return Product.objects.filter_by_category(self.categories.all()).exclude(id=self.id).distinct()


class ProductImage(models.Model):
    """Model definition for ProductImage."""

    product = models.ForeignKey("Product", on_delete=models.CASCADE, related_name="images")
    image = models.ImageField(upload_to="products")

    class Meta:
        """Meta definition for ProductImage."""

        verbose_name = "ProductImage"
        verbose_name_plural = "ProductImages"

    def __str__(self):
        """Unicode representation of ProductImage."""
        return f"{self.product.name} - {self.image.name}"

server/apps/base/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    """Home view."""

    template_name = "base/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["title"] = "Home"

        return context


class AboutView(TemplateView):
    """About view."""

    template_name = "base/about.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["title"] = "About"

        return context


class ContactView(TemplateView):
    """Contact view."""

    template_name = "base/contact.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["title"] = "Contact"

        return context

server/apps/category/views.py
from django.views.generic import DetailView

from server.apps.category.models import Category


class CategoryView(DetailView):
    """Category Product List view."""

    model = Category
    context_object_name = "category"

    template_name = "products/shop.html"

    def get_context_data(self, **kwargs):
        return {
            **super().get_context_data(**kwargs),
            "title": self.object.name,
            "products": self.object.get_products(),
        }

server/apps/product/views.py
from django.views.generic import DetailView, ListView

from server.apps.product.models import Product


class ProductListView(ListView):
    """Product List view."""

    model = Product
    context_object_name = "products"

    paginate_by = 11

    template_name = "products/shop.html"

    def get_context_data(self, **kwargs):
        return {**super().get_context_data(**kwargs), "title": "Shop"}


class ProductDetailView(DetailView):
    """Product Detail view."""

    model = Product
    context_object_name = "product"

    template_name = "products/product.html"

    def get_context_data(self, **kwargs):
        return {**super().get_context_data(**kwargs), "title": self.object.name}

server/apps/product/templates/products/product.html
{% extends 'base/layout.html' %}

{% load static %}



{% block content %}

<!-- Main -->
<main id="content">
  <!-- Breadcrumb -->
  <section class="py-2 bg-gray-2">
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb breadcrumb-site py-0 d-flex justify-content-center">
          <li class="breadcrumb-item"><a class="text-decoration-none text-body" href="{% url 'base:home' %}">Home</a>
          </li>
          <li class="breadcrumb-item pl-0 d-flex align-items-center"><a class="text-decoration-none text-body"
              href="{% url 'product:list' %}">Shop</a></li>
          <li class="breadcrumb-item active pl-0 d-flex align-items-center" aria-current="page">{{ product.name }}</li>
        </ol>
      </nav>
    </div>
  </section>

  <!-- Product Details -->
  <section class="pt-11 pb-9 pb-lg-10 product-details-layout-1">
    <div class="container">
      <div class="row">
        <div class="col-md-6 pr-xl-9 mb-8 mb-md-0">
          <div class="galleries-product galleries-product-01 position-relative d-flex">
            <div class="slick-slider slider-for mx-0 pl-xl-5"
              data-slick-options='{"slidesToShow": 1,"vertical":true, "autoplay":false,"dots":false,"arrows":false,"asNavFor": ".slider-nav","responsive":[{"breakpoint": 1200,"settings": {"vertical": false}}]}'>

              {% for item in product.images.all %}
              <!-- Product Image -->
              <div class="box px-0">
                <div class="card p-0 rounded-0 border-0">
                  <a href="{{ item.image.url }}" class="card-img" data-gtf-mfp="true" data-gallery-id="02">
                    <img src="{{ item.image.url }}" alt="{{ product.name }}" class="w-100 modal-image" />
                  </a>
                </div>
              </div>
              {% endfor %}

              <!-- Product Image -->
              <div class="box px-0">
                <div class="card p-0 rounded-0 border-0">
                  <img src="assets/images/product/product-17.jpg" class="card-img w-100" alt="product gallery" />
                  <div class="card-img-overlay d-inline-flex flex-column align-items-center justify-content-center">
                    <a href="https://www.youtube.com/watch?v=6v2L2UGZJAM" data-gtf-mfp="true"
                      data-mfp-options='{"type":"iframe","preloader":false}'
                      class="btn btn-rounded text-secondary btn-light w-90px h-90 my-lg-4 d-flex justify-content-center align-items-center rounded-circle fs-30">
                      <i class="fas fa-play"></i>
                    </a>
                  </div>
                </div>
              </div>
            </div>
            <div class="slick-slider slider-nav mx-n1 mx-xl-0"
              data-slick-options='{"slidesToShow": 4,"vertical":true, "autoplay":false,"dots":false,"arrows":false,"asNavFor": ".slider-for","focusOnSelect": true,"responsive":[{"breakpoint": 1200,"settings": {"vertical": false}}]}'>

              {% for item in product.images.all %}
              <!-- Product Image -->
              <div class="box px-1 px-xl-0 py-4 pt-xl-0">
                <img src="{{ item.image.url }}" class="w-100 modal-image-footer" alt="product gallery" />
              </div>
              {% endfor %}

            </div>
          </div>
        </div>
        <div class="col-md-6">
          <p class="d-flex align-items-center">
            <span class="fs-18 text-secondary font-weight-bold">${{ product.price }}</span>
          </p>
          <h2 class="fs-24 mb-2">{{ product.name }}</h2>
          <p class="mb-4 mr-xl-6">{{ product.description }}</p>
          <p class="mb-2"></p>
          <ul class="list-unstyled border-top pt-5 mt-5">
            <li class="row mb-2">
              <span class="d-block col-4 col-lg-2 text-secondary font-weight-600 fs-14">Categories:</span>
              <span class="d-block col-8 col-lg-10 fs-14">{{ product.get_categories }}</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </section>

  <!-- Recommended Products -->
  <section class="pt-10 pt-lg-13 pb-9 pb-lg-11 border-top">
    <div class="container">
      <h3 class="text-center fs-34 mb-8">You May Also Like</h3>
      <div class="slick-slider mx-n2"
        data-slick-options='{"slidesToShow": 4,"dots":false,"arrows":false,"responsive":[{"breakpoint": 1368,"settings": {"arrows":false,"dots":true}},{"breakpoint": 1200,"settings": {"slidesToShow":3,"arrows":false,"dots":true}},{"breakpoint": 992,"settings": {"slidesToShow":2,"arrows":false,"dots":true}},{"breakpoint": 768,"settings": {"slidesToShow": 2,"arrows":false,"dots":true}},{"breakpoint": 576,"settings": {"slidesToShow": 1,"arrows":false,"dots":true}}]}'>

        {% for item in product.related_products %}

        <!-- Product -->
        <div class="box">
          <div class="card border-0 product">
            <div class="position-relative">
              <img class="shopping-image shopping-image-xl" src="{{ item.image.url }}" alt="{{ item.name }}" />
              <div class="card-img-overlay d-flex p-3">
                <div></div>
                <div class="my-auto w-100 content-change-vertical">
                  <a href="{% url 'product:detail' pk=item.id %}" data-toggle="tooltip" data-placement="left"
                    title="View products"
                    class="add-to-cart ml-auto d-flex align-items-center justify-content-center text-secondary bg-white hover-white bg-hover-secondary w-48px h-48px rounded-circle mb-2">
                    <svg class="icon icon-shopping-bag-open-light fs-24">
                      <use xlink:href="#icon-shopping-bag-open-light"></use>
                    </svg>
                  </a>
                  <a href="#" data-toggle="tooltip" data-placement="left" title="Quick view"
                    class="preview ml-auto d-md-flex align-items-center justify-content-center cursor-pointer text-secondary bg-white hover-white bg-hover-secondary w-48px h-48px rounded-circle mb-2 d-none">
                    <span data-toggle="modal" data-target="#quick-view-{{ item.id }}">
                      <svg class="icon icon-eye-light fs-24">
                        <use xlink:href="#icon-eye-light"></use>
                      </svg>
                    </span>
                  </a>
                </div>
              </div>
            </div>
            <div class="card-body pt-4 text-center">
              <p class="card-text font-weight-bold fs-16 mb-1 text-secondary">
                <span>${{ item.price }}</span>
              </p>
              <h2 class="card-title fs-15 font-weight-500 mb-2"><a href="{% url 'product:detail' pk=item.id %}">{{
                  item.name }}</a></h2>
            </div>
          </div>
        </div>

        {% endfor %}
      </div>
    </div>
  </section>
</main>

{% endblock content %}



{% block icons %}

<!-- Icons -->
<svg aria-hidden="true" style="position: absolute; width: 0; height: 0; overflow: hidden" version="1.1"
  xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <defs>
    <symbol id="icon-shopping-bag-open-light" viewBox="0 0 32 32">
      <path
        d="M27 5.25h-22c-0.966 0.001-1.749 0.784-1.75 1.75v18c0.001 0.966 0.784 1.749 1.75 1.75h22c0.966-0.001 1.749-0.784 1.75-1.75v-18c-0.001-0.966-0.784-1.749-1.75-1.75h-0zM5 6.75h22c0.138 0 0.25 0.112 0.25 0.25v2.25h-22.5v-2.25c0-0.138 0.112-0.25 0.25-0.25h0zM27 25.25h-22c-0.138-0-0.25-0.112-0.25-0.25v-14.25h22.5v14.25c-0 0.138-0.112 0.25-0.25 0.25h-0zM21.75 14c0 3.176-2.574 5.75-5.75 5.75s-5.75-2.574-5.75-5.75v0c0-0.414 0.336-0.75 0.75-0.75s0.75 0.336 0.75 0.75v0c0 2.347 1.903 4.25 4.25 4.25s4.25-1.903 4.25-4.25v0c0-0.414 0.336-0.75 0.75-0.75s0.75 0.336 0.75 0.75v0z">
      </path>
    </symbol>
    <symbol id="icon-eye-light" viewBox="0 0 32 32">
      <path
        d="M30.685 15.695c-0.043-0.097-1.083-2.404-3.405-4.726-2.153-2.153-5.858-4.72-11.28-4.72s-9.127 2.567-11.28 4.72c-2.322 2.322-3.362 4.629-3.405 4.726-0.041 0.090-0.065 0.194-0.065 0.304s0.024 0.215 0.067 0.309l-0.002-0.005c0.043 0.097 1.083 2.404 3.405 4.725 2.153 2.153 5.858 4.719 11.28 4.719s9.127-2.566 11.28-4.719c2.322-2.322 3.362-4.628 3.405-4.725 0.041-0.090 0.065-0.194 0.065-0.305s-0.024-0.215-0.067-0.309l0.002 0.005zM16 24.249c-3.922 0-7.348-1.427-10.181-4.241-1.16-1.152-2.152-2.472-2.939-3.919l-0.044-0.089c0.83-1.536 1.823-2.856 2.982-4.008l0.001-0.001c2.833-2.815 6.259-4.242 10.181-4.242s7.348 1.427 10.181 4.242c1.16 1.153 2.152 2.472 2.939 3.92l0.044 0.089c-0.796 1.525-4.784 8.249-13.164 8.249zM16 10.25c-3.176 0-5.75 2.574-5.75 5.75s2.574 5.75 5.75 5.75c3.176 0 5.75-2.574 5.75-5.75v0c-0.004-3.174-2.576-5.746-5.75-5.75h-0zM16 20.25c-2.347 0-4.25-1.903-4.25-4.25s1.903-4.25 4.25-4.25c2.347 0 4.25 1.903 4.25 4.25v0c-0.003 2.346-1.904 4.247-4.25 4.25h-0z">
      </path>
    </symbol>
  </defs>
</svg>

{% endblock icons %}



{% block modals %}


{% for item in products %}

<!-- Quick View Modal -->
<div class="modal fade quick-view" id="quick-view-{{ item.id }}" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header border-0 py-0">
        <button type="button" class="close fs-32" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body pt-0">
        <div class="row">
          <!-- Product Images -->
          <div class="col-md-6 pr-xl-5 mb-8 mb-md-0 pl-xl-8">
            <div class="galleries-product product galleries-product-02 position-relative">
              <div class="position-absolute pos-fixed-top-right z-index-2">
                <div class="content-change-vertical"></div>
              </div>

              <div class="view-slider-for mx-0">
                {% for item in item.images.all %}
                <!-- Image -->
                <div class="box px-0">
                  <div class="card p-0 rounded-0 border-0">
                    <a href="{{ item.image.url }}" class="card-img">
                      <img class="modal-image" src="{{ item.image.url }}" alt="{{ item.name }}" />
                    </a>
                  </div>
                </div>
                {% endfor %}
              </div>

              <div class="view-slider-nav mx-n1">
                {% for item in item.images.all %}
                <!-- Image -->
                <div class="box py-4 px-1 cursor-pointer">
                  <img class="modal-image-footer" src="{{ item.image.url }}" alt="{{ item.name }}" />
                </div>
                {% endfor %}
              </div>
            </div>
          </div>

          <!-- Product info -->
          <div class="col-md-6 pl-xl-6 pr-xl-8">
            <p class="d-flex align-items-center">
              <span class="fs-18 text-secondary font-weight-bold">${{ item.price }}</span>
            </p>
            <h2 class="fs-24 mb-2">{{ item.name }}</h2>
            <p class="mb-4 mr-xl-6">{{ item.description }}</p>
            <p class="mb-2"></p>
            <ul class="list-unstyled border-top pt-5 mt-5">
              <li class="row mb-2">
                <span class="d-block col-4 col-lg-2 text-secondary font-weight-600 fs-14">Categories:</span>
                <span class="d-block col-8 col-lg-10 fs-14">{{ item.get_categories }}</span>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endfor %}

{% endblock modals %}

server/apps/product/templates/products/shop.html
{% extends 'base/layout.html' %}

{% load static %}


{% block content %}
<!-- Main -->
<main id="content">
  <!-- Breadcrumb -->
  <section class="py-2 bg-gray-2">
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb breadcrumb-site py-0 d-flex justify-content-center">
          <li class="breadcrumb-item"><a class="text-decoration-none text-body" href="{% url 'base:home' %}">Home</a>
          </li>
          <li class="breadcrumb-item active pl-0 d-flex align-items-center" aria-current="page">{{ title }}</li>
        </ol>
      </nav>
    </div>
  </section>

  <!-- Title -->
  <section>
    <div class="container container-xl">
      <h2 class="text-center mt-9 mb-8">{{ title }}</h2>
    </div>
  </section>

  <!-- Product List -->
  <section class="mt-7">
    <div class="container container-xl">
      <div class="row">
        {% for item in products %}
        <!-- Product small -->
        <div
          class="{% if forloop.counter0 < 4 or forloop.counter0 > 6 %}col-xl-3{% endif %} col-lg-4 col-md-6 mb-6 mb-lg-7">
          <div class="card border-0 product" data-animate="fadeInUp">
            <div class="position-relative">
              <img
                class="shopping-image{% if forloop.counter0 > 3 or forloop.counter0 < 7 %}-1{% endif %} shopping-image-xl"
                src="{{ item.image.url }}" alt="{{ item.name }}" />
              <div class="card-img-overlay d-flex p-3">
                <div></div>
                <div class="my-auto w-100 content-change-vertical">
                  <a href="{% url 'product:detail' pk=item.id %}" data-toggle="tooltip" data-placement="left"
                    title="View products"
                    class="add-to-cart ml-auto d-flex align-items-center justify-content-center text-secondary bg-white hover-white bg-hover-secondary w-48px h-48px rounded-circle mb-2">
                    <svg class="icon icon-shopping-bag-open-light fs-24">
                      <use xlink:href="#icon-shopping-bag-open-light"></use>
                    </svg>
                  </a>
                  <a href="#" data-toggle="tooltip" data-placement="left" title="Quick view"
                    class="preview ml-auto d-md-flex align-items-center justify-content-center cursor-pointer text-secondary bg-white hover-white bg-hover-secondary w-48px h-48px rounded-circle mb-2 d-none">
                    <span data-toggle="modal" data-target="#quick-view-{{ item.id }}">
                      <svg class="icon icon-eye-light fs-24">
                        <use xlink:href="#icon-eye-light"></use>
                      </svg>
                    </span>
                  </a>
                </div>
              </div>
            </div>
            <div class="card-body pt-4 text-center">
              <p class="card-text font-weight-bold fs-16 mb-1 text-secondary">
                <span>${{ item.price }}</span>
              </p>

              <h2 class="card-title fs-15 font-weight-500 mb-2">
                <a href="{% url 'product:detail' pk=item.id %}">{{ item.name }}</a>
              </h2>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </section>
  <!-- End Products -->

  <!-- Pagination -->
  <section class="pb-lg-13 pb-11">
    <nav>
      <ul class="pagination justify-content-center align-items-center mb-0 fs-16 font-weight-600">

        {% if page_obj.has_previous %}
        <li class="page-item fs-18 d-none d-sm-block">
          <a class="page-link rounded-circle w-40px h-40 p-0 justify-content-center align-items-center d-flex"
            href="{% url 'product:list' %}?page={{ page_obj.previous_page_number }}" tabindex="-1"><i
              class="far fa-angle-double-left"></i></a>
        </li>
        {% endif %}

        {% for page_number in page_obj.paginator.get_elided_page_range %}
        {% if page_number == page_obj.paginator.ELLIPSIS %}
        <li class="page-item disabled">
          <a class="page-link rounded-circle w-40px h-40 p-0 justify-content-center align-items-center d-flex">...</a>
        </li>
        {% else %}
        <li class="page-item {% if page_number == page_obj.number %}active" aria-current="page" {% else %}"{% endif %}>
          <a class="page-link rounded-circle w-40px h-40 p-0 justify-content-center align-items-center d-flex"
            href="{% url 'product:list' %}?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item fs-18 d-none d-sm-block">
          <a class="page-link rounded-circle w-40px h-40 p-0 justify-content-center align-items-center d-flex"
            href="{% url 'product:list' %}?page={{ page_obj.next_page_number }}"><i
              class="far fa-angle-double-right"></i></a>
        </li>
        {% endif %}
      </ul>
    </nav>
  </section>
  <!-- End Pagination -->
</main>
{% endblock content %}


{% block icons %}
<!-- Icons -->
<svg aria-hidden="true" style="position: absolute; width: 0; height: 0; overflow: hidden" version="1.1"
  xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <defs>
    <symbol id="icon-shopping-bag-open-light" viewBox="0 0 32 32">
      <path
        d="M27 5.25h-22c-0.966 0.001-1.749 0.784-1.75 1.75v18c0.001 0.966 0.784 1.749 1.75 1.75h22c0.966-0.001 1.749-0.784 1.75-1.75v-18c-0.001-0.966-0.784-1.749-1.75-1.75h-0zM5 6.75h22c0.138 0 0.25 0.112 0.25 0.25v2.25h-22.5v-2.25c0-0.138 0.112-0.25 0.25-0.25h0zM27 25.25h-22c-0.138-0-0.25-0.112-0.25-0.25v-14.25h22.5v14.25c-0 0.138-0.112 0.25-0.25 0.25h-0zM21.75 14c0 3.176-2.574 5.75-5.75 5.75s-5.75-2.574-5.75-5.75v0c0-0.414 0.336-0.75 0.75-0.75s0.75 0.336 0.75 0.75v0c0 2.347 1.903 4.25 4.25 4.25s4.25-1.903 4.25-4.25v0c0-0.414 0.336-0.75 0.75-0.75s0.75 0.336 0.75 0.75v0z">
      </path>
    </symbol>
    <symbol id="icon-eye-light" viewBox="0 0 32 32">
      <path
        d="M30.685 15.695c-0.043-0.097-1.083-2.404-3.405-4.726-2.153-2.153-5.858-4.72-11.28-4.72s-9.127 2.567-11.28 4.72c-2.322 2.322-3.362 4.629-3.405 4.726-0.041 0.090-0.065 0.194-0.065 0.304s0.024 0.215 0.067 0.309l-0.002-0.005c0.043 0.097 1.083 2.404 3.405 4.725 2.153 2.153 5.858 4.719 11.28 4.719s9.127-2.566 11.28-4.719c2.322-2.322 3.362-4.628 3.405-4.725 0.041-0.090 0.065-0.194 0.065-0.305s-0.024-0.215-0.067-0.309l0.002 0.005zM16 24.249c-3.922 0-7.348-1.427-10.181-4.241-1.16-1.152-2.152-2.472-2.939-3.919l-0.044-0.089c0.83-1.536 1.823-2.856 2.982-4.008l0.001-0.001c2.833-2.815 6.259-4.242 10.181-4.242s7.348 1.427 10.181 4.242c1.16 1.153 2.152 2.472 2.939 3.92l0.044 0.089c-0.796 1.525-4.784 8.249-13.164 8.249zM16 10.25c-3.176 0-5.75 2.574-5.75 5.75s2.574 5.75 5.75 5.75c3.176 0 5.75-2.574 5.75-5.75v0c-0.004-3.174-2.576-5.746-5.75-5.75h-0zM16 20.25c-2.347 0-4.25-1.903-4.25-4.25s1.903-4.25 4.25-4.25c2.347 0 4.25 1.903 4.25 4.25v0c-0.003 2.346-1.904 4.247-4.25 4.25h-0z">
      </path>
    </symbol>
  </defs>
</svg>
{% endblock icons %}

{% block modals %}

{% for product in products %}
<!-- Quick View Modal -->
<div class="modal fade quick-view" id="quick-view-{{ product.id }}" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header border-0 py-0">
        <button type="button" class="close fs-32" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body pt-0">
        <div class="row">
          <!-- Product Images -->
          <div class="col-md-6 pr-xl-5 mb-8 mb-md-0 pl-xl-8">
            <div class="galleries-product product galleries-product-02 position-relative">
              <div class="position-absolute pos-fixed-top-right z-index-2">
                <div class="content-change-vertical"></div>
              </div>

              <div class="view-slider-for mx-0">
                {% for item in product.images.all %}
                <!-- Image -->
                <div class="box px-0">
                  <div class="card p-0 rounded-0 border-0">
                    <a href="{{ item.image.url }}" class="card-img">
                      <img class="modal-image" src="{{ item.image.url }}" alt="{{ item.name }}" />
                    </a>
                  </div>
                </div>
                {% endfor %}
              </div>

              <div class="view-slider-nav mx-n1">
                {% for item in product.images.all %}
                <!-- Image -->
                <div class="box py-4 px-1 cursor-pointer">
                  <img class="modal-image-footer" src="{{ item.image.url }}" alt="{{ product.name }}" />
                </div>
                {% endfor %}
              </div>
            </div>
          </div>

          <!-- Product info -->
          <div class="col-md-6 pl-xl-6 pr-xl-8">
            <p class="d-flex align-items-center">
              <span class="fs-18 text-secondary font-weight-bold">${{ product.price }}</span>
            </p>

            <h2 class="fs-24 mb-2">{{ product.name }}</h2>

            <p class="mb-4 mr-xl-6">{{ product.description }}</p>

            <p class="mb-2"></p>

            <ul class="list-unstyled border-top pt-5 mt-5">
              <li class="row mb-2">
                <span class="d-block col-4 col-lg-2 text-secondary font-weight-600 fs-14">Categories:</span>
                <span class="d-block col-8 col-lg-10 fs-14">{{ product.get_categories }}</span>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endfor %}

{% endblock modals %}